### PR TITLE
Handle cases where att has its own attribute of name="label"

### PR DESCRIPTION
**Pull request by ariutta**
Hello,

Thanks for creating this plugin. Unfortunately, when I just tried using it on an xgmml file from a third party source, it threw this error:

```
Traceback (most recent call last):
  File "exrna_mapper.py", line 37, in <module>
    _main()
  File "exrna_mapper.py", line 18, in _main
    g = networkxgmml.XGMMLReader(options.XGMML)
  File "/Users/andersriutta/.virtualenvs/exrna-mapper/lib/python2.7/site-packages/networkxgmml.py", line 111, in XGMMLReader
    parser.parseFile(file)
  File "/Users/andersriutta/.virtualenvs/exrna-mapper/lib/python2.7/site-packages/networkxgmml.py", line 83, in parseFile
    self._parser.ParseFile(file)
  File "/Users/andersriutta/.virtualenvs/exrna-mapper/lib/python2.7/site-packages/networkxgmml.py", line 67, in _end_element
    self._graph.add_node(self._current_obj['id'], label=self._current_obj['label'], **self._current_attr)
TypeError: add_node() got multiple values for keyword argument 'label'
```

It's because of a conflict that happens when a `node` element has attribute of `label="anything"`, and that `node` element also has an `att` element with its own attribute of `name="label"`, as you can see in [this example](https://github.com/ariutta/networkxxgmml/blob/cbcf0aeec4cb9bfa371b87946f556387863522d4/example/mirtarbase-sample.xgmml#L13).

My pull request changes `label` to `@label` when it's the value of a name attribute for the `att` element. This is based on the [JXON](https://developer.mozilla.org/en-US/docs/JXON) convention, but I'm open to alternatives if there's a more standard xgmml way of doing this.

### CODE REVIEW

**Comment by ariutta** [comment]
For that matter, any of the [valid attribute names](http://cgi5.cs.rpi.edu/research/groups/pb/punin/public_html/XGMML/DOC/xgmml_schema.html#element_Line_Link01C99A10) for graph, graphics, node, and edge could cause the same problem:
- id  
- name  
- label  
- labelanchor  
- type  
- weight  
- edgeanchor 
- source  
- target
- directed  
- Vendor  
- Rootnode  
- Scale  
- Layout  
- Graphic
- x  
- y  
- z  
- w  
- h  
- d  
- image  
- bitmap  
- width  
- arrow  
- capstyle  
- joinstyle  
- smooth  
- splinesteps  
- justify  
- font  
- background  
- foreground  
- extent  
- start  
- style  
- stipple  
- visible  
- fill  
- outline  
- anchor  
  (there are also the xlink attribute names, which couldn't prefixed by `@`)
- xlink:href  
- xlink:role  
- xlink:arcrole  
- xlink:title  
- xlink:show  
- xlink:actuate  
- xml:lang  
- xml:space  

It might be easiest to just prefix all `att` element attribute name values with `@`, except for the xlink ones.

**Comment by ariutta** [comment]
For now, I'm just changing `label` to `@label` in case of conflict.

**Comment by informationsea** [comment]
Sorry, I cannot review soon. I will review your changes in a week.

**Comment by ariutta** [comment]
Sounds good. I think "label" might be the only thing we need to worry
about. I don't see how the others could cause problems.

**Comment by ariutta** [comment]
Any chance of approving this pull request? I'd rather not publish another version to the Python Package Index.

**Comment by informationsea** [comment]
Sorry for slow reply. I just merged and I'm preparing for uploading to PyPi.

**Comment by ariutta** [comment]
Great! Thanks.

**Pull request merged**
